baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gipyeong-lee.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false
  - scope:
        path: "_posts"
    type: "posts"
    values:
      comments: true      
  - scope:
      path: "images"
    values:
      image: true
include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed